export type EsmaName = {
  no: number;
  arabic: string;
  translit: string;
  meaning: string;
};

export const ESMA_UL_HUSNA: EsmaName[] = [
  { no: 1, arabic: "اَلرَّحْمٰنُ", translit: "Er-Rahmân", meaning: "Bütün yaratılmışlara rahmet ve nimet veren." },
  { no: 2, arabic: "اَلرَّحِيمُ", translit: "Er-Rahîm", meaning: "Ahirette yalnız mü'minlere merhamet eden." },
  { no: 3, arabic: "اَلْمَلِكُ", translit: "El-Melik", meaning: "Mülkün, kâinatın gerçek sahibi olan." },
  { no: 4, arabic: "اَلْقُدُّوسُ", translit: "El-Kuddûs", meaning: "Her türlü eksiklikten uzak, mukaddes olan." },
  { no: 5, arabic: "اَلسَّلَامُ", translit: "Es-Selâm", meaning: "Esenlik veren, kullarını selâmete çıkaran." },
  { no: 6, arabic: "اَلْمُؤْمِنُ", translit: "El-Mü'min", meaning: "Güven veren, emin kılan, koruyan." },
  { no: 7, arabic: "اَلْمُهَيْمِنُ", translit: "El-Müheymin", meaning: "Her şeyi gözetip koruyan." },
  { no: 8, arabic: "اَلْعَزِيزُ", translit: "El-Azîz", meaning: "Mutlak galip, izzet sahibi." },
  { no: 9, arabic: "اَلْجَبَّارُ", translit: "El-Cebbâr", meaning: "Dilediğini zorla yaptıran, kırılanı onaran." },
  { no: 10, arabic: "اَلْمُتَكَبِّرُ", translit: "El-Mütekebbir", meaning: "Büyüklükte eşi olmayan." },
  { no: 11, arabic: "اَلْخَالِقُ", translit: "El-Hâlik", meaning: "Her şeyi yoktan yaratan." },
  { no: 12, arabic: "اَلْبَارِئُ", translit: "El-Bâri'", meaning: "Her şeyi kusursuz ve uyumlu yaratan." },
  { no: 13, arabic: "اَلْمُصَوِّرُ", translit: "El-Musavvir", meaning: "Her şeye şekil ve suret veren." },
  { no: 14, arabic: "اَلْغَفَّارُ", translit: "El-Gaffâr", meaning: "Günahları çokça bağışlayan." },
  { no: 15, arabic: "اَلْقَهَّارُ", translit: "El-Kahhâr", meaning: "Her şeye üstün gelen, kahreden." },
  { no: 16, arabic: "اَلْوَهَّابُ", translit: "El-Vehhâb", meaning: "Karşılıksız bol bol veren." },
  { no: 17, arabic: "اَلرَّزَّاقُ", translit: "Er-Rezzâk", meaning: "Bütün canlıların rızkını veren." },
  { no: 18, arabic: "اَلْفَتَّاحُ", translit: "El-Fettâh", meaning: "Kapalı kapıları açan, zorlukları gideren." },
  { no: 19, arabic: "اَلْعَلِيمُ", translit: "El-Alîm", meaning: "Her şeyi hakkıyla bilen." },
  { no: 20, arabic: "اَلْقَابِضُ", translit: "El-Kâbıd", meaning: "Dilediğine darlık veren, tutan." },
  { no: 21, arabic: "اَلْبَاسِطُ", translit: "El-Bâsıt", meaning: "Dilediğine genişlik ve bolluk veren." },
  { no: 22, arabic: "اَلْخَافِضُ", translit: "El-Hâfıd", meaning: "Dilediğini alçaltan." },
  { no: 23, arabic: "اَلرَّافِعُ", translit: "Er-Râfi'", meaning: "Dilediğini yükselten." },
  { no: 24, arabic: "اَلْمُعِزُّ", translit: "El-Mu'iz", meaning: "Dilediğine izzet ve şeref veren." },
  { no: 25, arabic: "اَلْمُذِلُّ", translit: "El-Müzil", meaning: "Dilediğini zillete düşüren." },
  { no: 26, arabic: "اَلسَّمِيعُ", translit: "Es-Semî'", meaning: "Her şeyi işiten." },
  { no: 27, arabic: "اَلْبَصِيرُ", translit: "El-Basîr", meaning: "Her şeyi gören." },
  { no: 28, arabic: "اَلْحَكَمُ", translit: "El-Hakem", meaning: "Mutlak hüküm veren hâkim." },
  { no: 29, arabic: "اَلْعَدْلُ", translit: "El-Adl", meaning: "Mutlak adalet sahibi." },
  { no: 30, arabic: "اَللَّطِيفُ", translit: "El-Latîf", meaning: "En ince işlerin sırrını bilen, lütuf sahibi." },
  { no: 31, arabic: "اَلْخَبِيرُ", translit: "El-Habîr", meaning: "Her şeyin iç yüzünden haberdar olan." },
  { no: 32, arabic: "اَلْحَلِيمُ", translit: "El-Halîm", meaning: "Cezada acele etmeyen, yumuşak davranan." },
  { no: 33, arabic: "اَلْعَظِيمُ", translit: "El-Azîm", meaning: "Azamet sahibi, pek yüce." },
  { no: 34, arabic: "اَلْغَفُورُ", translit: "El-Gafûr", meaning: "Günahları örten, mağfiret eden." },
  { no: 35, arabic: "اَلشَّكُورُ", translit: "Eş-Şekûr", meaning: "Az amele çok sevap veren." },
  { no: 36, arabic: "اَلْعَلِيُّ", translit: "El-Aliyy", meaning: "Yüceler yücesi olan." },
  { no: 37, arabic: "اَلْكَبِيرُ", translit: "El-Kebîr", meaning: "Büyüklükte sınırı olmayan." },
  { no: 38, arabic: "اَلْحَفِيظُ", translit: "El-Hafîz", meaning: "Her şeyi koruyup saklayan." },
  { no: 39, arabic: "اَلْمُقِيتُ", translit: "El-Mukît", meaning: "Bedenlerin ve ruhların gıdasını veren." },
  { no: 40, arabic: "اَلْحَسِيبُ", translit: "El-Hasîb", meaning: "Kulların hesabını gören, yeten." },
  { no: 41, arabic: "اَلْجَلِيلُ", translit: "El-Celîl", meaning: "Celâl ve azamet sahibi." },
  { no: 42, arabic: "اَلْكَرِيمُ", translit: "El-Kerîm", meaning: "Keremi ve ihsanı bol olan." },
  { no: 43, arabic: "اَلرَّقِيبُ", translit: "Er-Rakîb", meaning: "Bütün varlığı gözetleyen." },
  { no: 44, arabic: "اَلْمُجِيبُ", translit: "El-Mucîb", meaning: "Duaları kabul edip karşılık veren." },
  { no: 45, arabic: "اَلْوَاسِعُ", translit: "El-Vâsi'", meaning: "Rahmeti ve ilmi geniş olan." },
  { no: 46, arabic: "اَلْحَكِيمُ", translit: "El-Hakîm", meaning: "Bütün işleri hikmetli olan." },
  { no: 47, arabic: "اَلْوَدُودُ", translit: "El-Vedûd", meaning: "Sâlih kullarını seven, sevilmeye layık olan." },
  { no: 48, arabic: "اَلْمَجِيدُ", translit: "El-Mecîd", meaning: "Şanı ve şerefi büyük olan." },
  { no: 49, arabic: "اَلْبَاعِثُ", translit: "El-Bâis", meaning: "Ölüleri dirilten, peygamber gönderen." },
  { no: 50, arabic: "اَلشَّهِيدُ", translit: "Eş-Şehîd", meaning: "Her yerde hazır ve şahit olan." },
  { no: 51, arabic: "اَلْحَقُّ", translit: "El-Hakk", meaning: "Varlığı hiç değişmeyen, gerçek olan." },
  { no: 52, arabic: "اَلْوَكِيلُ", translit: "El-Vekîl", meaning: "Kendisine tevekkül edenlerin işini üstlenen." },
  { no: 53, arabic: "اَلْقَوِيُّ", translit: "El-Kaviyy", meaning: "Kudreti sonsuz olan." },
  { no: 54, arabic: "اَلْمَتِينُ", translit: "El-Metîn", meaning: "Kuvveti çok sağlam olan." },
  { no: 55, arabic: "اَلْوَلِيُّ", translit: "El-Veliyy", meaning: "Mü'minlerin dostu, yardımcısı." },
  { no: 56, arabic: "اَلْحَمِيدُ", translit: "El-Hamîd", meaning: "Her türlü övgüye layık olan." },
  { no: 57, arabic: "اَلْمُحْصِي", translit: "El-Muhsî", meaning: "Her şeyi tek tek sayan, bilen." },
  { no: 58, arabic: "اَلْمُبْدِئُ", translit: "El-Mübdi'", meaning: "Her şeyi ilk defa yaratan." },
  { no: 59, arabic: "اَلْمُعِيدُ", translit: "El-Muîd", meaning: "Yarattığını yok edip tekrar diriltecek olan." },
  { no: 60, arabic: "اَلْمُحْيِي", translit: "El-Muhyî", meaning: "Can veren, dirilten." },
  { no: 61, arabic: "اَلْمُمِيتُ", translit: "El-Mümît", meaning: "Ölümü yaratan." },
  { no: 62, arabic: "اَلْحَيُّ", translit: "El-Hayy", meaning: "Ezelî ve ebedî diri olan." },
  { no: 63, arabic: "اَلْقَيُّومُ", translit: "El-Kayyûm", meaning: "Kendi kendine var olan, her şeyi ayakta tutan." },
  { no: 64, arabic: "اَلْوَاجِدُ", translit: "El-Vâcid", meaning: "Hiçbir şeye ihtiyacı olmayan, dilediğini bulan." },
  { no: 65, arabic: "اَلْمَاجِدُ", translit: "El-Mâcid", meaning: "Kadri ve şanı büyük, keremi bol olan." },
  { no: 66, arabic: "اَلْوَاحِدُ", translit: "El-Vâhid", meaning: "Zâtında ve sıfatlarında tek olan." },
  { no: 67, arabic: "اَلْاَحَدُ", translit: "El-Ehad", meaning: "Bölünmeyen, eşi benzeri olmayan bir." },
  { no: 68, arabic: "اَلصَّمَدُ", translit: "Es-Samed", meaning: "Her şey kendisine muhtaç, O hiçbir şeye muhtaç olmayan." },
  { no: 69, arabic: "اَلْقَادِرُ", translit: "El-Kâdir", meaning: "Dilediğini yapmaya gücü yeten." },
  { no: 70, arabic: "اَلْمُقْتَدِرُ", translit: "El-Muktedir", meaning: "Kudreti her şeye nafiz olan." },
  { no: 71, arabic: "اَلْمُقَدِّمُ", translit: "El-Mukaddim", meaning: "Dilediğini öne geçiren." },
  { no: 72, arabic: "اَلْمُؤَخِّرُ", translit: "El-Muahhir", meaning: "Dilediğini geriye bırakan." },
  { no: 73, arabic: "اَلْاَوَّلُ", translit: "El-Evvel", meaning: "Başlangıcı olmayan, ilk olan." },
  { no: 74, arabic: "اَلْآخِرُ", translit: "El-Âhir", meaning: "Sonu olmayan, bâki olan." },
  { no: 75, arabic: "اَلظَّاهِرُ", translit: "Ez-Zâhir", meaning: "Varlığı apaçık olan." },
  { no: 76, arabic: "اَلْبَاطِنُ", translit: "El-Bâtın", meaning: "Zâtının hakikati gizli olan." },
  { no: 77, arabic: "اَلْوَالِي", translit: "El-Vâlî", meaning: "Kâinatı idare eden." },
  { no: 78, arabic: "اَلْمُتَعَالِي", translit: "El-Müteâlî", meaning: "Yaratılmışların vasıflarından yüce olan." },
  { no: 79, arabic: "اَلْبَرُّ", translit: "El-Berr", meaning: "Kullarına iyilik ve ihsanı bol olan." },
  { no: 80, arabic: "اَلتَّوَّابُ", translit: "Et-Tevvâb", meaning: "Tevbeleri kabul eden." },
  { no: 81, arabic: "اَلْمُنْتَقِمُ", translit: "El-Müntakim", meaning: "Suçluları adaletle cezalandıran." },
  { no: 82, arabic: "اَلْعَفُوُّ", translit: "El-Afüvv", meaning: "Affı çok olan." },
  { no: 83, arabic: "اَلرَّؤُوفُ", translit: "Er-Raûf", meaning: "Çok şefkatli, çok esirgeyen." },
  { no: 84, arabic: "مَالِكُ الْمُلْكِ", translit: "Mâlikü'l-Mülk", meaning: "Mülkün ebedî sahibi." },
  { no: 85, arabic: "ذُو الْجَلَالِ وَالْاِكْرَامِ", translit: "Zü'l-Celâli ve'l-İkrâm", meaning: "Celâl, azamet ve ikram sahibi." },
  { no: 86, arabic: "اَلْمُقْسِطُ", translit: "El-Muksit", meaning: "Bütün işlerini denk ve adaletli yapan." },
  { no: 87, arabic: "اَلْجَامِعُ", translit: "El-Câmi'", meaning: "Dilediğini dilediği zaman toplayan." },
  { no: 88, arabic: "اَلْغَنِيُّ", translit: "El-Ganiyy", meaning: "Hiçbir şeye ihtiyacı olmayan, zengin." },
  { no: 89, arabic: "اَلْمُغْنِي", translit: "El-Mugnî", meaning: "Dilediğini zengin kılan." },
  { no: 90, arabic: "اَلْمَانِعُ", translit: "El-Mâni'", meaning: "Dilemediği şeye engel olan." },
  { no: 91, arabic: "اَلضَّارُّ", translit: "Ed-Dârr", meaning: "Elem ve zarar verecekleri yaratan." },
  { no: 92, arabic: "اَلنَّافِعُ", translit: "En-Nâfi'", meaning: "Fayda ve hayır verecekleri yaratan." },
  { no: 93, arabic: "اَلنُّورُ", translit: "En-Nûr", meaning: "Âlemleri nurlandıran, hidayet veren." },
  { no: 94, arabic: "اَلْهَادِي", translit: "El-Hâdî", meaning: "Hidayete erdiren, doğru yolu gösteren." },
  { no: 95, arabic: "اَلْبَدِيعُ", translit: "El-Bedî'", meaning: "Eşsiz ve örneksiz yaratan." },
  { no: 96, arabic: "اَلْبَاقِي", translit: "El-Bâkî", meaning: "Varlığının sonu olmayan." },
  { no: 97, arabic: "اَلْوَارِثُ", translit: "El-Vâris", meaning: "Bütün mülkün gerçek sahibi olarak kalan." },
  { no: 98, arabic: "اَلرَّشِيدُ", translit: "Er-Reşîd", meaning: "İrşad eden, bütün işleri isabetli olan." },
  { no: 99, arabic: "اَلصَّبُورُ", translit: "Es-Sabûr", meaning: "Çok sabırlı olan, acele etmeyen." },
];
